# Generated by Django 3.2.8 on 2021-10-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0005_auto_20211031_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shape',
        ),
    ]
